name: GAG Bot

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
    - cron: "2-59/5 * * * *"   # :02 :07 :12 ... (backup)
  workflow_dispatch:         # allow manual runs from the Actions tab

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests
      - name: Run poster
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python bot.py
